services:
  db:
      image: mysql:latest
      container_name: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: peluchBoost
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - mysql-data:/var/lib/mysql



  bootapp:
    image: peluchboost
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
    mysql-data: