CREATE TABLE IF NOT EXISTS quotes (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    quote TEXT NOT NULL,
    author VARCHAR(255) NOT NULL
);

INSERT INTO quotes (quote, author) VALUES
    ("The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    ("It always seems impossible until it’s done.", "Nelson Mandela"),
    ("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    ("The future depends on what you do today.", "Mahatma Gandhi"),
    ("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
    ("Whether you think you can, or you think you can't – you're right.", "Henry Ford"),
    ("The way to get started is to quit talking and begin doing.", "Walt Disney"),
    ("Act as if what you do makes a difference. It does.", "William James"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    ("You miss 100% of the shots you don’t take.", "Wayne Gretzky"),
    ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
    ("Success is not final, failure is not fatal: It is the courage to continue that counts.", "Winston Churchill"),
    ("Believe you can and you’re halfway there.", "Theodore Roosevelt"),
    ("Everything you’ve ever wanted is on the other side of fear.", "George Addair"),
    ("Do one thing every day that scares you.", "Eleanor Roosevelt"),
    ("Opportunities don’t happen, you create them.", "Chris Grosser"),
    ("Don’t be afraid to give up the good to go for the great.", "John D. Rockefeller"),
    ("If everything seems under control, you’re not going fast enough.", "Mario Andretti"),
    ("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"),
    ("Success is how high you bounce when you hit bottom.", "George S. Patton"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("Failure is another stepping stone to greatness.", "Oprah Winfrey"),
    ("What would you do if you weren’t afraid?", "Sheryl Sandberg"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("Do not wait to strike till the iron is hot, but make it hot by striking.", "William B. Sprague"),
    ("Everything has beauty, but not everyone sees it.", "Confucius"),
    ("Dream big and dare to fail.", "Norman Vaughan"),
    ("Courage is resistance to fear, mastery of fear – not absence of fear.", "Mark Twain"),
    ("Only put off until tomorrow what you are willing to die having left undone.", "Pablo Picasso"),
    ("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
    ("We may encounter many defeats but we must not be defeated.", "Maya Angelou"),
    ("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
    ("The best revenge is massive success.", "Frank Sinatra"),
    ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    ("Keep your face always toward the sunshine—and shadows will fall behind you.", "Walt Whitman"),
    ("It is never too late to be what you might have been.", "George Eliot"),
    ("Act as if what you do makes a difference. It does.", "William James"),
    ("Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"),
    ("The only impossible journey is the one you never begin.", "Tony Robbins"),
    ("The purpose of our lives is to be happy.", "Dalai Lama"),
    ("Life is what happens when you’re busy making other plans.", "John Lennon"),
    ("Get busy living or get busy dying.", "Stephen King"),
    ("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("Don’t let yesterday take up too much of today.", "Will Rogers"),
    ("Do what you feel in your heart to be right – for you’ll be criticized anyway.", "Eleanor Roosevelt"),
    ("Believe you can and you’re halfway there.", "Theodore Roosevelt"),
    ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
    ("We become what we think about.", "Earl Nightingale"),
    ("What we achieve inwardly will change outer reality.", "Plutarch"),
    ("I never dreamed about success. I worked for it.", "Estée Lauder"),
    ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
    ("Keep your face always toward the sunshine—and shadows will fall behind you.", "Walt Whitman");


